#!/bin/bash

# OS-specific checks for presence of greadlink
case `uname` in
*Darwin*)
  READLINK=greadlink
  GREADLINKLOCATION=`which greadlink`
  if [ -z ${GREADLINKLOCATION} ]; then
    # install should have complained already, but maybe configuration changed
    echo "Missing greadlink. Please 'brew install coreutils'"
    exit 1
  fi
  ;;
*)
  READLINK=readlink
  ;;
esac

SRC=$("$READLINK" -f "${BASH_SOURCE}")
HOME_DIR=${SRC%/*}
JAR_NAME=$HOME_DIR/gia.jar

if [ ! -f "$JAR_NAME" ]; then
  echo "Couldn't find the gia jars to execute, aborting."
  echo "Looked for $JAR_NAME"
  exit 2
fi

STDLIB=$HOME_DIR/lib/stdlib.gia

LOAD_LIST="$STDLIB $@"
DECL_LIST=""

function run_gia {
    LOAD_SCRIPT=""
    for FILE in $LOAD_LIST
    do
        LOAD_SCRIPT+="use \"$FILE\"; "
    done

    java -jar $JAR_NAME "$LOAD_SCRIPT $DECL_LIST" "User input" "$@"
}

run_gia "\"Loaded\""

while read -e -p '(gia) ' LINE
do
    if [[ ! -z ${LINE// /} ]]
    then
        COMMAND=$(echo $LINE | cut -d " " -f 1)
        ARGS=$(echo "$LINE" | awk '{ for (i=2; i<NF; i++) printf $i" " ; print $NF }')
        case $COMMAND in
            "exit")
                exit 0
                ;;
            "reload")
                run_gia "\"Done\""
                ;;
            "use")
                if [ ! -f $ARGS ]
                then
                    echo "File $ARGS not found"
                elif [[ $LOAD_LIST == *$ARGS* ]]
                then
                    echo "File $ARGS already loaded"
                else
                    OLD_LOAD_LIST=$LOAD_LIST
                    LOAD_LIST+=" $ARGS"
                    run_gia "\"Done\"" || LOAD_LIST=$OLD_LOAD_LIST
                fi
                ;;
            "shell")
                $ARGS
                ;;
            *)
                if [[ $LINE =~ (^[ ]*[a-zA-Z][a-zA-Z0-9_]*[ ]*=.*;[ ]*$) ]]
                then
                    OLD_DECL_LIST=$DECL_LIST
                    DECL_LIST+="$LINE"
                    RESULT=$(run_gia "$COMMAND") && echo "$COMMAND = $RESULT" || (DECL_LIST=$OLD_DECL_LIST; echo -e "$RESULT")
                elif [[ $LINE =~ (;[ ]*$) ]]
                then
                    OLD_DECL_LIST=$DECL_LIST
                    DECL_LIST+="$LINE"
                    run_gia "\"OK\"" || DECL_LIST=$OLD_DECL_LIST
                else
                    run_gia "$LINE"
                fi
        esac
    fi
    history -s "$LINE"
done
